{% set version = '1.1.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringi
  version: {{ version|replace("-", "_") }}

source:
  fn: stringi_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/stringi_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/stringi/stringi_{{ version }}.tar.gz
  sha256: 9590360b96627b18d7bed273deedabda4283dbae7d41c0a0ba78a58e6aa95188

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('stringi')"  # [not win]
    - "\"%R%\" -e \"library('stringi')\""  # [win]

about:
  home: http://www.gagolewski.com/software/stringi
  license: FOSS
  license_file: LICENSE
  summary: 'Allows for fast, correct, consistent, portable, as well as convenient character string/text
    processing in every locale and any native encoding. Owing to the use of the ICU
    library, the package provides R users with platform-independent functions known
    to Java, Perl, Python, PHP, and Ruby programmers. Available features include: pattern
    searching (e.g., with ICU Java-like regular expressions or the Unicode Collation Algorithm), random
    string generation, case mapping, string transliteration, concatenation, Unicode normalization,
    date-time formatting and parsing, etc.'
  license_family: OTHER

extra:
  recipe-maintainers:
    - ocefpaf
    - mariusvniekerk
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
